---
- hosts: localhost
  become: true
  tasks:
    - name: Pull Docker image
      command: docker pull garv09/calculator:latest

    - name: Stop old container
      command: docker stop calculator
      ignore_errors: yes

    - name: Remove old container
      command: docker rm calculator
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name calculator garv09/calculator:latest
